"use client";

import React, { useState, useCallback } from "react";
import { cn } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DiffView } from "@/components/DiffView";
import { InlineLoader } from "@/components/LoadingStates";
import type { RewriteSection } from "@/lib/ai-pipeline";

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

export interface RewritePreviewProps {
  /** Sections generated by the AI rewrite pipeline. */
  rewrites: RewriteSection[];
  /** Called when the user accepts or rejects an individual section. */
  onSectionToggle?: (section: string, accepted: boolean) => void;
  /** Called when the user clicks "接受全部修改". */
  onAcceptAll?: () => void;
  /** Called when the user clicks "保留原文". */
  onRejectAll?: () => void;
  /** External control of accepted sections. */
  acceptedSections?: Set<string>;
  className?: string;
}

/* ------------------------------------------------------------------ */
/*  Section label mapping                                              */
/* ------------------------------------------------------------------ */

const sectionLabels: Record<string, string> = {
  summary: "个人简介",
  experience: "工作经历",
  skills: "技能",
  education: "教育背景",
  projects: "项目经验",
  certifications: "证书",
  languages: "语言能力",
};

function getSectionLabel(section: string): string {
  return sectionLabels[section] ?? section;
}

/* ------------------------------------------------------------------ */
/*  Confidence Indicator                                               */
/* ------------------------------------------------------------------ */

function ConfidenceIndicator({ impact }: { impact: string }) {
  const colorMap: Record<string, string> = {
    high: "bg-green-100 text-green-700 border-green-200",
    medium: "bg-amber-100 text-amber-700 border-amber-200",
    low: "bg-gray-100 text-gray-600 border-gray-200",
  };

  const labelMap: Record<string, string> = {
    high: "高影响",
    medium: "中等影响",
    low: "低影响",
  };

  const normalizedImpact = impact?.toLowerCase() ?? "low";

  return (
    <span
      className={cn(
        "inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium",
        colorMap[normalizedImpact] ?? colorMap.low,
      )}
    >
      {labelMap[normalizedImpact] ?? normalizedImpact}
    </span>
  );
}

/* ------------------------------------------------------------------ */
/*  Single Section Card                                                */
/* ------------------------------------------------------------------ */

interface SectionCardProps {
  rewrite: RewriteSection;
  accepted: boolean;
  onToggle: (accepted: boolean) => void;
  defaultExpanded?: boolean;
}

function SectionCard({
  rewrite,
  accepted,
  onToggle,
  defaultExpanded = false,
}: SectionCardProps) {
  const [showDiff, setShowDiff] = useState(defaultExpanded);

  return (
    <div
      className={cn(
        "rounded-xl border bg-white shadow-sm transition-all",
        accepted
          ? "border-green-200 ring-1 ring-green-200"
          : "border-gray-200",
      )}
    >
      {/* Section header */}
      <div className="flex items-center justify-between border-b border-gray-100 px-5 py-3">
        <div className="flex items-center gap-3">
          <h4 className="text-sm font-semibold text-gray-900">
            {getSectionLabel(rewrite.section)}
          </h4>
          {rewrite.impact_improvement && (
            <ConfidenceIndicator impact={rewrite.impact_improvement} />
          )}
        </div>

        <div className="flex items-center gap-2">
          {/* Accept / Reject toggle */}
          <button
            type="button"
            onClick={() => onToggle(!accepted)}
            className={cn(
              "inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium transition-colors",
              "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500",
              accepted
                ? "bg-green-100 text-green-700 hover:bg-green-200"
                : "bg-gray-100 text-gray-600 hover:bg-gray-200",
            )}
            aria-label={accepted ? `拒绝修改：${getSectionLabel(rewrite.section)}` : `接受修改：${getSectionLabel(rewrite.section)}`}
            aria-pressed={accepted}
          >
            {accepted ? (
              <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            ) : (
              <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v12m6-6H6" />
              </svg>
            )}
            {accepted ? "已接受" : "接受"}
          </button>

          {/* Expand/collapse diff */}
          <button
            type="button"
            onClick={() => setShowDiff(!showDiff)}
            className="inline-flex items-center gap-1 rounded-lg px-3 py-1.5 text-xs font-medium text-gray-500 transition-colors hover:bg-gray-100 hover:text-gray-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500"
            aria-expanded={showDiff}
            aria-label={showDiff ? "收起差异视图" : "展开差异视图"}
          >
            <svg
              className={cn("h-3.5 w-3.5 transition-transform", showDiff && "rotate-180")}
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
            {showDiff ? "收起" : "查看详情"}
          </button>
        </div>
      </div>

      {/* Section body */}
      {showDiff && (
        <div className="p-5">
          {/* Side-by-side on desktop, stacked on mobile */}
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
            {/* Original */}
            <div>
              <div className="mb-2 flex items-center gap-1.5">
                <span className="inline-block h-2 w-2 rounded-full bg-red-400" />
                <span className="text-xs font-medium text-gray-500">原文</span>
              </div>
              <div className="rounded-lg border border-red-200 bg-red-50/50 p-3 text-sm text-gray-700 leading-relaxed">
                {rewrite.original}
              </div>
            </div>

            {/* Rewritten */}
            <div>
              <div className="mb-2 flex items-center gap-1.5">
                <span className="inline-block h-2 w-2 rounded-full bg-green-400" />
                <span className="text-xs font-medium text-gray-500">优化后</span>
              </div>
              <div className="rounded-lg border border-green-200 bg-green-50/50 p-3 text-sm text-gray-700 leading-relaxed">
                {rewrite.rewritten}
              </div>
            </div>
          </div>

          {/* Inline diff */}
          <div className="mt-4">
            <DiffView
              original={rewrite.original}
              rewritten={rewrite.rewritten}
            />
          </div>

          {/* Reasoning */}
          {rewrite.reasoning && (
            <div className="mt-4 rounded-lg bg-blue-50 p-3">
              <p className="text-xs font-medium text-blue-700">为什么修改</p>
              <p className="mt-1 text-sm text-blue-800 leading-relaxed">
                {rewrite.reasoning}
              </p>
            </div>
          )}

          {/* Keywords added */}
          {rewrite.keywords_added && rewrite.keywords_added.length > 0 && (
            <div className="mt-3">
              <p className="mb-1.5 text-xs font-medium text-gray-500">新增关键词</p>
              <div className="flex flex-wrap gap-1.5">
                {rewrite.keywords_added.map((kw) => (
                  <Badge key={kw} variant="default">
                    {kw}
                  </Badge>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  Main Component                                                     */
/* ------------------------------------------------------------------ */

function RewritePreview({
  rewrites,
  onSectionToggle,
  onAcceptAll,
  onRejectAll,
  acceptedSections: externalAccepted,
  className,
}: RewritePreviewProps) {
  // Internal state fallback if no external control is provided
  const [internalAccepted, setInternalAccepted] = useState<Set<string>>(new Set());
  const acceptedSections = externalAccepted ?? internalAccepted;

  const handleToggle = useCallback(
    (section: string, accepted: boolean) => {
      setInternalAccepted((prev) => {
        const next = new Set(prev);
        if (accepted) next.add(section);
        else next.delete(section);
        return next;
      });
      onSectionToggle?.(section, accepted);
    },
    [onSectionToggle],
  );

  const handleAcceptAll = useCallback(() => {
    const all = new Set(rewrites.map((r) => r.section));
    setInternalAccepted(all);
    onAcceptAll?.();
  }, [rewrites, onAcceptAll]);

  const handleRejectAll = useCallback(() => {
    setInternalAccepted(new Set());
    onRejectAll?.();
  }, [onRejectAll]);

  const acceptedCount = acceptedSections.size;
  const totalCount = rewrites.length;

  if (rewrites.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <p className="text-sm text-gray-500">暂无修改建议</p>
      </div>
    );
  }

  return (
    <div className={cn("space-y-4", className)}>
      {/* Summary bar */}
      <div className="flex flex-col gap-3 rounded-xl border border-gray-200 bg-white p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-3">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-100">
            <svg className="h-4 w-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.992 0l3.181 3.183a8.25 8.25 0 0013.803-3.7M4.031 9.865a8.25 8.25 0 0113.803-3.7l3.181 3.182" />
            </svg>
          </div>
          <div>
            <p className="text-sm font-semibold text-gray-900">
              共 {totalCount} 个章节优化
            </p>
            <p className="text-xs text-gray-500">
              已选择 {acceptedCount}/{totalCount} 个修改
            </p>
          </div>
        </div>

        <div className="flex gap-2">
          <Button
            variant="default"
            size="sm"
            onClick={handleAcceptAll}
            disabled={acceptedCount === totalCount}
          >
            接受全部修改
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handleRejectAll}
            disabled={acceptedCount === 0}
          >
            保留原文
          </Button>
        </div>
      </div>

      {/* Section cards */}
      {rewrites.map((rewrite) => (
        <SectionCard
          key={rewrite.section}
          rewrite={rewrite}
          accepted={acceptedSections.has(rewrite.section)}
          onToggle={(accepted) => handleToggle(rewrite.section, accepted)}
        />
      ))}
    </div>
  );
}

RewritePreview.displayName = "RewritePreview";

export { RewritePreview };
export type { RewriteSection };
